name: PHP
on: [push]
jobs:
  ci:
    name: PHP
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
    - uses: actions/checkout@v3
    - run: composer install
      working-directory: api
    - run: ./vendor/bin/phpcs
      working-directory: api
    - run: ./vendor/bin/phpunit --coverage-text
      working-directory: api
